version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: kubsu
      POSTGRES_USER: kubsu
      POSTGRES_PASSWORD: kubsu
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: users-api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://kubsu:kubsu@db:5432/kubsu
    ports:
      - "8067:8067"
